# Generated by Django 2.2.7 on 2019-11-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewt_count',
            field=models.IntegerField(default=0),
        ),
    ]
