# Generated by Django 2.2.7 on 2019-11-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20191128_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='netx_post',
            new_name='next_post',
        ),
    ]
